["setup.cfg".black]
line-length = 80
target-version = ['py38']
include = 'functions'
exclude = '\.pyc|.json'


["setup.cfg".flake8]
ignore = "D107,D202,D203,D401,Q000"
max-line-length = 80
inline-quotes = "double"

["setup.cfg".isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true