["pyproject.toml".tool.black]
line-length = 80
target-version = ['py38']
include = 'functions'
exclude = '\.pyc|.json'

["pyproject.toml".tool.pylint]
disable = {"disable"=["invalid-name", "missing-module-docstring"]}

["setup.cfg".flake8]
ignore = "D107,D104,D202,D203,D210,D401,Q000,C812,C815,E203"
exclude = functions/test/*
max-line-length = 80
inline-quotes = "double"

["setup.cfg".isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

["setup.cfg".mypy]
python_version = 3.8
ignore_missing_imports = True
